//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropBox_BLL.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DropboxWebhook
    {
        public int DW_Id { get; set; }
        public string DW_Body { get; set; }
        public Nullable<System.DateTime> DW_TimeStamp { get; set; }
        public byte DW_Processed { get; set; }
        public Nullable<System.DateTime> DW_ProcessTimeStamp { get; set; }
    }
}
